'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LinkedInExpressExtractor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Afghanistan,93,AF 
        '''Albania,355,AL 
        '''Algeria,213,DZ 
        '''Andorra,376,AD 
        '''Angola,244,AO 
        '''Antarctica,672,AQ 
        '''Argentina,54,AR 
        '''Armenia,374,AM 
        '''Aruba,297,AW 
        '''Australia,61,AU 
        '''Austria,43,AT 
        '''Azerbaijan,994,AZ 
        '''Bahrain,973,BH 
        '''Bangladesh,880,BD 
        '''Belarus,375,BY 
        '''Belgium,32,BE 
        '''Belize,501,BZ 
        '''Benin,229,BJ 
        '''Bhutan,975,BT 
        '''Bolivia,591,BO 
        '''Bosnia and Herzegovina,387,BA 
        '''Botswana,267,BW 
        '''Brazil,55,BR 
        '''British Indian Ocean Territory,246,IO 
        '''Brunei,673,BN 
        '''Bulgaria,359,BG 
        '''Burkina Faso,226,BF 
        '''Burund [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Countries() As String
            Get
                Return ResourceManager.GetString("Countries", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
